[project]
name = "create-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain[anthropic]>=1.2.0",
    "langchain-openai>=1.1.6",
]
